services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    environment:
      - JUPYTER_ENABLE_LAB=yes
    user: root
    command: /bin/bash -c "python -m ipykernel install --name=python3 --display-name 'Python 3.9' && jupyter lab --ip=0.0.0.0 --no-browser --allow-root --NotebookApp.token=''"
